config/routes.rb
Rails.application.routes.draw do

root 'static_pages#dashboard'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :todo_lists  do
    resources :todo_items
  end
  resources :users
  resources :bank_items
  resources :groceries

  mount Commontator::Engine => '/commontator'

  resources :profiles

end

app/models/bank_item.rb
class BankItem < ActiveRecord::Base
  belongs_to :user
  acts_as_commontable
end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
	belongs_to :user
	acts_as_commontable
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  validates_presence_of :name
  acts_as_commontable
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name
	has_many :todo_items
  acts_as_commontable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bank_items, dependent: :destroy
  has_one :grocery
  validates_presence_of :email
  acts_as_commenter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bank_items_controller.rb
class BankItemsController < ApplicationController
  def index
    @bank_items = BankItem.all
  end

  def new
    @bank_item = BankItem.new

  end

  def create
    @user = current_user
    @bank_item = @user.bank_items.new(bank_items_params)
  	if @bank_item.save
  		redirect_to bank_item_path(@bank_item)
  	else
  		render :new
  	end
  end


  def edit
    @bank_item = BankItem.find(params[:id])
  end

  def update
    @bank_item = current_user.bank_items.new(bank_items_params)
    if @bank_item.update(bank_items_params)
      redirect_to bank_item_path(@bank_item)
    else
      render :edit
    end
  end

  def show
    @bank_item = current_user.bank_items.find(params[:id])
    commontator_thread_show(@bank_item)
  end

  def destroy
    @bank_item = current_user.bank_items.find(params[:id])
    @bank_item.destroy
    redirect_to bank_items_path
  end

private
  def bank_items_params
    params.require(:bank_item).permit(:name, :priority, :amount, :due_date, :mark_complete, :user_id)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  before_action :grocery, except: [:index, :new, :create]

  def index
  	@groceries = Grocery.all
  end

  def new
  	@grocery = Grocery.new
  end

  def create
  	@grocery = Grocery.new(grocery_params)
  	if @grocery.save
  		redirect_to groceries_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
    if @grocery.update(grocery_params)
      redirect_to grocery_path(@grocery)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    grocery_name = @grocery.name
    @grocery.destroy
    redirect_to groceries_path
  end

  private

  def grocery_params
  	params.require(:grocery).permit(:name, :completed)
  end

  def grocery
  	@grocery = Grocery.find(params[:id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  	@users = User.where.not(id: current_user.id)
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def dashboard
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :todo_list
  before_action :todo_item, only: [:edit, :update, :destroy, :show]

  def index
    @todo_items = @todo_list.todo_items
  end

  def show
  end

  def new
    @todo_item = TodoItem.new
  end

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    if @todo_item.save
      redirect_to todo_list_path(@todo_list)
    else
      render:new
    end
  end

  def edit
  end

  def update
    @todo_item = TodoItem.find(params[:id])
    if @todo_item.update(todo_item_params)
      redirect_to todo_list_path(@todo_list) #, @todo_item)
    else
      render :edit
    end
  end

  def destroy
    @todo_item.destroy
    redirect_to todo_list_path(@todo_list)
  end

  private
    def todo_item_params
      params.require(:todo_item).permit(:name, :complete)
    end

    def todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def todo_item
      @todo_item = TodoItem.find(params[:id])
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :todo_list, except: [:index, :new, :create]
  # before_action :todo_item, only: [:show]

  def index
    @todo_lists = TodoList.all
  end
 
  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
      if @todo_list.save
        redirect_to todo_list_path(@todo_list)
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to todo_list_path(@todo_list)
    else
      render :edit
    end
  end

  def show
    @todo_items = @todo_list.todo_items
  end


  def destroy
    @todo_list.destroy
    redirect_to todo_lists_path
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:name, :description)
  end

  def todo_list
    @todo_list = TodoList.find(params[:id])
  end

  # def todo_item
  #   @todo_item = TodoItem.find(params[:id])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_items_helper.rb
module BankItemsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/commontator/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/profiles/index.html.erb
<div class="container">
	<% if @users.any? %>
		<div class="row">
			<% @users.each do |user| %>
			 <div class="col-md-4">
			 	 <div class="row">
					 <div class="col-md-12 text-uppercase text-bold text-center">
							<%= user.first_name %> 
					  </div>
					</div>
					<%= link_to (image_tag user.image.url(:medium)), profile_path(user) %> 
			</div>
		<%end%>
	</div>
		</ul>
	<% else %>
		<h3 class='center'>No users!</h3>
	<% end %>
</div>

app/views/profiles/show.html.erb
<hr/>
<%= image_tag @user.image.url(:medium)%> 
<br/>

<h6 class='text-uppercase'><%= @user.first_name %> ACCOUNTS</h6>
<%= link_to "BANKR", bank_item_path(@user) %> |
<%= link_to "GROCRY", grocery_path(@user) %> |
<%= link_to "SYNRGY", todo_list_path(@user) %>

app/views/static_pages/dashboard.html.erb
  <!-- < button_to 'Log Out', destroy_user_session_path, method: :delete > -->
<!-- <h2>Welcome < current_user.first_name > </h2> -->

<div class='center remindr-logo'>
  <%=link_to image_tag('remindr_logo.png'), '/'%>
</div>

<div class = "dashboard-logos row">
  <div class = "col s12 m12 l4">
    <%= link_to(image_tag('bankr_logo.png'), bank_items_path) %>
  </div>
  <div class = "col s12 m12 l4">
    <%= link_to(image_tag('grocry_logo.png'), groceries_path) %>
  </div>
  <div class = "col s12 m12 l4">
    <%= link_to(image_tag('synrgy_logo.png'), todo_lists_path) %>
  </div>
<div>

<% if (current_user.image.url != "/images/original/missing.png") %>
	<%= image_tag current_user.image.url(:medium) %> <hr/>
<% end %>
<%= link_to 'BANKR', bank_items_path %> |
<%= link_to 'GROCRY', groceries_path %> |
<%= link_to 'SYNRGY', todo_lists_path %> |
<%= link_to 'EDIT PROFILE', edit_user_registration_path %> |
<%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %> |
<%= link_to 'PROFILES', profiles_path %>