config/routes.rb
Rails.application.routes.draw do

root 'static_pages#dashboard'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :todo_lists  do
    resources :todo_items
  end
  resources :users
  resources :bank_items
  resources :groceries

  mount Commontator::Engine => '/commontator'

  resources :profiles

end

app/models/bank_item.rb
class BankItem < ActiveRecord::Base
  belongs_to :user
  acts_as_commontable
end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
	belongs_to :user
	acts_as_commontable
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  validates_presence_of :name
  acts_as_commontable
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name
	has_many :todo_items
  acts_as_commontable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bank_items, dependent: :destroy
  has_one :grocery
  validates_presence_of :email
  acts_as_commenter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bank_items_controller.rb
class BankItemsController < ApplicationController
  def index
    @bank_items = BankItem.all
  end

  def new
    @bank_item = BankItem.new

  end

  def create
    @user = current_user
    @bank_item = @user.bank_items.new(bank_items_params)
  	if @bank_item.save
  		redirect_to bank_item_path(@bank_item)
  	else
  		render :new
  	end
  end


  def edit
    @bank_item = BankItem.find(params[:id])
  end

  def update
    @bank_item = current_user.bank_items.new(bank_items_params)
    if @bank_item.update(bank_items_params)
      redirect_to bank_item_path(@bank_item)
    else
      render :edit
    end
  end

  def show
    @bank_item = current_user.bank_items.find(params[:id])
    commontator_thread_show(@bank_item)
  end

  def destroy
    @bank_item = current_user.bank_items.find(params[:id])
    @bank_item.destroy
    redirect_to bank_items_path
  end

private
  def bank_items_params
    params.require(:bank_item).permit(:name, :priority, :amount, :due_date, :mark_complete, :user_id)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  before_action :grocery, except: [:index, :new, :create]

  def index
  	@groceries = Grocery.all
  end

  def new
  	@grocery = Grocery.new
  end

  def create
  	@grocery = Grocery.new(grocery_params)
  	if @grocery.save
  		redirect_to groceries_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
    if @grocery.update(grocery_params)
      redirect_to grocery_path(@grocery)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    grocery_name = @grocery.name
    @grocery.destroy
    redirect_to groceries_path
  end

  private

  def grocery_params
  	params.require(:grocery).permit(:name, :completed)
  end

  def grocery
  	@grocery = Grocery.find(params[:id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  	@users = User.where.not(id: current_user.id)
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def dashboard
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :todo_list
  before_action :todo_item, only: [:edit, :update, :destroy, :show]

  def index
    @todo_items = @todo_list.todo_items
  end

  def show
  end

  def new
    @todo_item = TodoItem.new
  end

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    if @todo_item.save
      redirect_to todo_list_path(@todo_list)
    else
      render:new
    end
  end

  def edit
  end

  def update
    @todo_item = TodoItem.find(params[:id])
    if @todo_item.update(todo_item_params)
      redirect_to todo_list_path(@todo_list) #, @todo_item)
    else
      render :edit
    end
  end

  def destroy
    @todo_item.destroy
    redirect_to todo_list_path(@todo_list)
  end

  private
    def todo_item_params
      params.require(:todo_item).permit(:name, :complete)
    end

    def todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def todo_item
      @todo_item = TodoItem.find(params[:id])
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :todo_list, except: [:index, :new, :create]
  # before_action :todo_item, only: [:show]

  def index
    @todo_lists = TodoList.all
  end
 
  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
      if @todo_list.save
        redirect_to todo_list_path(@todo_list)
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to todo_list_path(@todo_list)
    else
      render :edit
    end
  end

  def show
    @todo_items = @todo_list.todo_items
  end


  def destroy
    @todo_list.destroy
    redirect_to todo_lists_path
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:name, :description)
  end

  def todo_list
    @todo_list = TodoList.find(params[:id])
  end

  # def todo_item
  #   @todo_item = TodoItem.find(params[:id])
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_items_helper.rb
module BankItemsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/bank_items/_form.html.erb
<%= form_for @bank_item do |f|  %>
>>>>>>> various styles and buttons

<div class="form-box">
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :priority  %>
	<%= f.text_field :priority %>

  <%= f.label :amount %>
  <%= f.text_field :amount %>


  <%= f.label :due_date %>
  <%= f.date_field :due_date, order: [:month, :day, :year] %>
</div>

	<%= f.label :mark_complete %>
	<%= f.check_box :mark_complete %>

<hr>

<%= f.submit class: "green darken-4 white-text waves-effect waves-light btn" %>
<% end %>

app/views/bank_items/edit.html.erb
<h1>BankItems#edit</h1>
<%= render 'form' %>

app/views/bank_items/index.html.erb
<h1>These are your Bills</h1>

<% if @bank_items.any? %>
	<% @bank_items.each do |item| %>
	  <p>Bill to Pay: <%= link_to item.name, item %> </p>
	<% end %>
<% else %>

	<h3 class='center'> No Bankr has been added!</h3>
<% @bank_items.each do |item| %>
  <p>Bill to Pay: <%= link_to item.name, item %> </p>


	<%= link_to 'New Item', new_bank_item_path %>
<% end %>


<%= link_to 'Add A Bill', new_bank_item_path, class: "green darken-4 white-text waves-effect waves-light btn" %>
<br>

app/views/bank_items/new.html.erb
<h1 class = "green-text text-darken-4"> Bill Add</h1>
<%= render 'form' %>
<br />
<%= link_to 'Back To All Bills', bank_items_path, class: "green darken-4 white-text waves-effect waves-light btn" %>

app/views/bank_items/show.html.erb
<h1>Bank Items</h1>

  <p>Bill to pay: <%= @bank_item.name %></p>
  <p>Priority:<%= @bank_item.priority %></p>
  <p>Amount to pay: <%= @bank_item.amount %></p>
  <p>Bill is due on: <%= @bank_item.due_date %></p>

<%= commontator_thread(@bank_item) %>
<br>
<%= link_to 'All Bills', bank_items_path %>
<br>
<%= link_to 'ADD New Bill', new_bank_item_path %>
<br>
<%= link_to 'Delete Bill', bank_item_path, method: :delete %>
<br>
<%= link_to 'Edit item', edit_bank_item_path(@bank_item) %>
<br>

app/views/groceries/_form.html.erb
<%= form_for @grocery do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.label :completed %>
		<%= f.check_box :completed %>

    <%= f.submit class: "green darken-4 white-text waves-effect waves-light btn"%>

    <% f.hidden_field :user_id, :value => current_user.id %>

<% end %>

app/views/groceries/edit.html.erb
<h1>Grocrys</h1>
<br />
<%= render(partial: 'form') %>
<%= commontator_thread(@grocery) %>

app/views/groceries/index.html.erb
<h1>Your Grocry List:</h1>
<br />

<% if @groceries.any? %>
	<ul>
		<% @groceries.each do |grocery| %>
			<li>
				<h4>
  			<%= link_to grocery.name, edit_grocery_path(grocery) %>
				</h4>
  		</li>
  	<% end %>
  </ul>
<% else %>
  <h3>No grocrys, please add one!</h3>
<% end %>


<%= link_to 'dashboard', '/' %>
<%= link_to 'add grocrys', new_grocery_path, class: "green darken-4 white-text waves-effect waves-light btn" %>

app/views/groceries/new.html.erb
<h1>Add grocrys</h1>
<br />
<%= render(partial: 'form') %>

app/views/groceries/show.html.erb
<h1>Grocry Item:</h1>
<br />

<% if @grocery.name != 'nil' %>
		<%= @grocery.name %>
<% else %>
	<h3>No grocrys.</h3>
<% end %>


<br />
<%= link_to 'add more grocrys', new_grocery_path, class: "green darken-4 white-text waves-effect waves-light btn" %>
<%= link_to 'delete grocry item', grocery_path, method: :delete, data: {confirm: 'Sure you wanna delete?'}, class: "red darken-4 white-text waves-effect waves-light btn" %>
<%= link_to 'back to all grocrys', groceries_path, class: "green darken-4 white-text waves-effect waves-light btn" %>

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name, autofocus: true %>

	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.submit class: "green darken-4 white-text waves-effect waves-light btn" %>

<% end %>

app/views/todo_lists/edit.html.erb
<h1>Edit To Do List: <%= @todo_list.name %></h1>
<%= render(partial:'form') %>

app/views/todo_lists/index.html.erb
<h1>All Synrgys</h1>

<% if @todo_lists.any? %>
	<ul>
		<% @todo_lists.each do |list| %>
			<li>
  			<%= link_to list.name, todo_list_path(list) %>
  		</li>
  	<% end %>
  </ul>
<% else %>
  <h3>No to do lists, please add one!</h3>
<% end %>


<%= link_to 'Create a Synrgy', new_todo_list_path, class: "waves-effect waves-light btn blue-grey lighten-2" %>

app/views/todo_lists/new.html.erb
<h1>Create Synrgy</h1>
<%= render(partial:'form') %>

app/views/todo_lists/show.html.erb
<h1>List: <%= @todo_list.name %></h1>

<h4>List Description: <%= @todo_list.description %></h4>
<br />
<% if @todo_items.any? %>
	<ul>
		<% @todo_items.each do |todo_item| %>
			<li>
  			<%= link_to todo_item.name, edit_todo_list_todo_item_path(@todo_list, todo_item) %>
  		</li>
  	<% end %>
  </ul>
<% else %>
  <h3>No synrgys, please add one!</h3>
<% end %>

<%= link_to 'Add Items', new_todo_list_todo_item_path(@todo_list), class: "waves-effect waves-light btn green lighten-2" %>
<%= link_to 'Edit Synrgy', edit_todo_list_path, class: "waves-effect waves-light btn green lighten-2" %>
<%= link_to 'Delete Synrgy', todo_list_path(@todo_list), method: :delete, class: "waves-effect waves-light red lighten-1 btn", data: {confirm: 'Sure you want to delete this?'} %>